apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yaml-nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/880831ian/argocd-introduce.git
    targetRevision: main
    path: yaml-nginx-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/880831ian/argocd-introduce.git
    targetRevision: main
    path: helm-nginx-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
